# Generated by Django 4.2.21 on 2025-05-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignapplication',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_applications', to='accounts.influencerprofile'),
        ),
    ]
