# Generated by Django 4.2.21 on 2025-06-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_campaignapplication_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='facebook_page_category',
            field=models.CharField(blank=True, help_text='Facebook page category', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='facebook_page_name',
            field=models.CharField(blank=True, help_text='Facebook page name', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile or page URL'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='URL to profile picture from social media'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_conditions_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_conditions_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='facebook_page',
            field=models.CharField(blank=True, help_text='Facebook page ID', max_length=100),
        ),
    ]
