# Generated by Django 4.2.21 on 2025-06-22 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_influencerprofile_facebook_page_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('quote_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_posts', to='accounts.influencerprofile')),
            ],
            options={
                'verbose_name': 'Twitter Post',
                'verbose_name_plural': 'Twitter Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwitterMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('tweet_count', models.PositiveIntegerField(default=0)),
                ('listed_count', models.PositiveIntegerField(default=0)),
                ('avg_likes', models.FloatField(default=0.0)),
                ('avg_retweets', models.FloatField(default=0.0)),
                ('avg_replies', models.FloatField(default=0.0)),
                ('avg_quotes', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='Average engagement rate as percentage')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_metrics', to='accounts.influencerprofile')),
            ],
            options={
                'verbose_name': 'Twitter Metrics',
                'verbose_name_plural': 'Twitter Metrics',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
