# Generated by Django 4.2.21 on 2025-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_metrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
