# Generated by Django 4.2.21 on 2025-05-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_target_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='compensation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platforms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
