"""
Django settings for influenza_platform project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
import pymysql
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--s3*cr-elv5taf+4u=6y!0!&*$xpcw*xx)q#n_p3@!7ja49sx*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app', '.now.sh', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'messaging',
    'django.contrib.humanize',
    'social_django',
    'accounts',
    'campaigns',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'influenza_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'influenza_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'influenzadb_pockettorn',
        'USER': 'influenzadb_pockettorn',
        'PASSWORD': 'e62b5361b11e626d6a758fdc7d48ea369347794c',
        'HOST': 'hh8-y.h.filess.io',
        'PORT': '3307',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR / 'media')

# Social Authentication
AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
)

# Social Auth Keys
# These keys should be set in environment variables in production
SOCIAL_AUTH_FACEBOOK_KEY = '1210454147373721'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'f9cf819235cde673123f04ead7c12d6a'  # App Secret
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '896096319726-6mg6hecc6v2qpu2of2pvm4q47calr690.apps.googleusercontent.com'  # Client ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'  # Client Secret


# Facebook Page ID
FACEBOOK_PAGE_ID = '354214138121990'

# Social Auth Pipeline - to handle user type and profile creation
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'accounts.pipeline.set_user_type_influencer',  # Custom pipeline to set user type
    'accounts.pipeline.store_facebook_token',  # Store Facebook access token
    'accounts.pipeline_twitter.store_twitter_token',  # Custom pipeline to store Twitter token
    'accounts.pipeline_twitter.fetch_twitter_metrics',  # Custom pipeline to fetch Twitter metrics
    'accounts.pipeline.redirect_to_appropriate_page',  # Custom pipeline to handle redirection
)

# Social Auth Settings
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/dashboard/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = reverse_lazy('influencer_profile_create') # Redirect new users to complete profile
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Facebook Scope
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'pages_show_list', 'pages_read_engagement', 'public_profile', 'user_link', 'instagram_basic']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email, picture.type(large), link, accounts{name,access_token,fan_count,followers_count,category}'
}

# Google Scope
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

# Twitter API Configuration
SOCIAL_AUTH_TWITTER_KEY = '1i1ekoUZbuv3iajV3xri8L4e4'  # API Key
SOCIAL_AUTH_TWITTER_SECRET = 'o65WuzQ0VpaOIxbej1GF3zrNPpvbSt9aOreJJCdo6LjszIAzO9'  # API Secret
SOCIAL_AUTH_TWITTER_REDIRECT_URI = 'https://influenza-platform.vercel.app/social-auth/complete/twitter/'


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'uk20.myserverhosts.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'privacy@influenza.ke'  # Replace with your actual Gmail address
EMAIL_HOST_PASSWORD = '-KnfR0Wi0&BO'  # Replace with your Gmail app password
DEFAULT_FROM_EMAIL = 'Influenza Platform <privacy@influenza.ke>'

# # Configure logging
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'INFO',
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#         'file': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': 'debug.log',
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         '': {
#             'handlers': ['console', 'file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#     },
# }
